### ISSUE TITLE
Hardcoded config file

### ISSUE THREAD

**Issue by sebleblanc** [InTheMorning/Mercury#1]
Hello, I noticed that the config file path is hardcoded to a directory in your user's home folder.
Instead, you could use an environment variable, and if it is unset, defer to a standard path.

```
from os import environ, path

def get_config_file():
    config_file = environ.get('MERCURY_CONFIG')

    if config_file is None:
        base_path = environ.get('XDG_CONFIG_HOME', path.expanduser('~/.config'))
        config_file = path.join(base_path, 'mercury')

    return config_file

configfile = get_config_file()
````

This code will use the config file indicated by $MERCURY_CONFIG, otherwise it defaults to a sensible path in $XDG_CONFIG_HOME, and if this is also unset, it defers to ~/.config/mercury.

https://github.com/InTheMorning/Mercury/blob/781ea0d2fe6a591ab0f97cbbb7ff061d7a2bc9ed/main.py#L21

**Comment by InTheMorning** [comment]
fixed
